config/routes.rb
Rails.application.routes.draw do
  resources :wikis
  resources :wikis do
      resources :collaborations, only: [:new, :create, :destroy]
  end
  resources :charges, only: [:new, :create]
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      post :downgrade
    end
  end

  get 'about' => 'welcome#about'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborations
  has_many :shared_wikis, through: :collaborations, source: :wiki

  enum role: [:standard, :premium, :admin]
  before_save { self.role ||= :standard }

  def downgrade!
    wikis.update_all(private: false)
    self.update_attribute(:role, 'standard')
    self.standard!
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  validates :user, presence: true
  scope :pubic, -> { where(private: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to [@wiki]
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     @amount = 1500
     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )

     # Where the real magic happens
     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: @amount,
       description: "BigMoney Membership - #{current_user.email}",
       currency: 'usd'
     )

     flash[:notice] = "Thank you for the payment and upgrading your account to Premium, #{current_user.email}!"
     current_user.premium!
     redirect_to edit_user_registration_path

     # Stripe will send back CardErrors, with friendly messages
     # when something goes wrong.
     # This `rescue block` catches and displays those errors.
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
 end
   def new
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "BigMoney Membership - #{current_user.email}",
       amount: @amount
     }
   end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  def new
    @collaboration = Collaboration.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by(email: params[:search])
    if @user
      @collaboration = Collaboration.new(wiki: @wiki, user: @user)
      if @collaboration.save
        flash[:notice] = "Collaboration was saved."
        redirect_to edit_wiki_path(@wiki)
      else
        flash.now[:alert] = "There was an error saving the collaboration. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaboration = Collaboration.find(params[:id])
    @collaboration_user = User.find(@collaboration.user_id)

      if @collaboration.destroy
        flash[:notice] = "#{@collaboration_user.email} was removed as a collaborator."
        redirect_to edit_wiki_path(@wiki)
      else
        flash.now[:alert] = "There was an error removing this collaboration."
        redirect_to edit_wiki_path(@wiki)
      end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade
    @user = User.find(params[:id])

    if @user.downgrade!
      flash[:notice] = "You've been downgraded to standard. Your private wikis are now public."
      redirect_to edit_user_registration_path
    else
      flash[:error] = "There was an error creating your account. Please try again."
      redirect_to edit_user_registration_path
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if current_user.standard?
      @wikis = Wiki.where(private: false)
    else
      @wikis = policy_scope(Wiki)
    end
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    @collaboration = Collaboration.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    authorize @wiki

     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
   end

  def update
     @wiki = Wiki.friendly.find(params[:id])
     authorize @wiki
     @wiki.assign_attributes(wiki_params)
     if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
     end
   end

   def destroy
     @wiki = Wiki.friendly.find(params[:id])
     authorize @wiki

     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
   end

   private

   def wiki_params
     params.require(:wiki).permit(:title, :body, :private)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    require 'redcarpet'
    renderer = Redcarpet::Render::HTML.new
    extensions = { :autolink => true }
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
      <span>Amount: $15.00 </span>
    </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="1500"
    data-locale="auto"></script>
<% end %>

app/views/collaborations/_form.html.erb
<%= form_tag [wiki, collaboration] do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Add User" %>
<% end %>

app/views/collaborations/create.html.erb
<h1>Collaborations#create</h1>
<p>Find me in app/views/collaborations/create.html.erb</p>

app/views/collaborations/destroy.html.erb
<h1>Collaborations#destroy</h1>
<p>Find me in app/views/collaborations/destroy.html.erb</p>

app/views/collaborations/new.html.erb
<h1>Collaborations#new</h1>
<p>Find me in app/views/collaborations/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Informa</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Informa", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <li><%= link_to "Membership", new_charge_path %></li>

          <div class="pull-right user-info">
            <% if user_signed_in? %>
               Signed in as: <strong><%= current_user.email %></strong> | <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </div>
          <% else %>
               <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
               <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
      </ul>
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/downgrade.html.erb
<p>Find me in app/views/users/downgrade.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <% if current_user.admin? || current_user.premium? %>
      <%= f.label :private do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render 'collaborations/form', wiki: @wiki, collaboration: @collaboration %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
 <% @wikis.each do |wiki| %>
 <div class="media">
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to markdown(wiki.title), wiki %>
       <% if user_signed_in? && current_user == wiki.user %>
  				<td><%= link_to "Edit", edit_wiki_path(wiki.id) %></td>
  				<td><%= link_to "Delete", wiki, method: :delete, data: {confirm: "Are you sure?"} %></td>
			<% elsif user_signed_in? %>
			  <td><%= link_to "Edit", edit_wiki_path(wiki.id) %></td>
			<% end %>
     </h4>
   </div>

 </div>
 <% end %>


 <div class="col-md-4">
   <% if user_signed_in? %>
     <%= link_to "Create a new Wiki", new_wiki_path, class: "btn btn-success" %>
   <% end %>
 </div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render 'form' %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>

 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
   <div class="col-md-8">
     <h4>Collaborators:</h4>
       <% @wiki.collaborations.each do |c| %>
         <%= c.user.email %>
         <%= link_to "Delete Collaboration", [@wiki,c], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this collaboration?'} %>
       <% end %>
   </div>
 </div>